### ISSUE TITLE
关于rxjava +retrofit 封装网络访问

### ISSUE THREAD

**Issue by YoloHuang** [AxeChen/WanAndroid#1]
你好，看到你代码中有关于rxjava +retrofit 封装网络访问这块的知识。有个问题想请教一下。看到你将网络错误和数据错误全部都封装为ApiException。但是在最后subscribe的时候，onerror中传入的数据还是一个Throwable。这里ApiException并没有用到啊？那封装为ApiException的意义何在呢？
例如 ProjectListPresenter中的getProjectTreeList方法：
    override fun getProjectTreeList(cid: Int, isRefresh: Boolean) {
        if (isRefresh) {
            page = 0
        }
        var disposable: Disposable = model.getProjectListByCid(page, cid)
                .compose(ResponseTransformer.handleResult())
                .compose(scheduler?.applySchedulers())
                .subscribe(
                        { t ->
                            view?.getProjectListByCidSuccess(t, isRefresh)
                            page++
                        },
                        { t -> view?.getProjectListByCidFail(t.message!!) }
                )
        compositeDisposable.add(disposable)
    }

这其中，在 view?.getProjectListByCidFail(t.message!!) 部分，这里并没有用到ApiException。这里的message 是ApiException中的message吗？

**Comment by AxeChen** [comment]
ResponseTransformer 你可以看看这个类对异常的处理。这边把异常的处理都归到一起了。




------------------ 原始邮件 ------------------
发件人: "YoloHuang"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 中午11:15
收件人: "AxeChen/WanAndroid"<WanAndroid@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [AxeChen/WanAndroid] 关于rxjava +retrofit 封装网络访问 (#1)




你好，看到你代码中有关于rxjava +retrofit 封装网络访问这块的知识。有个问题想请教一下。看到你将网络错误和数据错误全部都封装为ApiException。但是在最后subscribe的时候，onerror中传入的数据还是一个Throwable。这里ApiException并没有用到啊？那封装为ApiException的意义何在呢？
 例如 ProjectListPresenter中的getProjectTreeList方法：
 override fun getProjectTreeList(cid: Int, isRefresh: Boolean) {
 if (isRefresh) {
 page = 0
 }
 var disposable: Disposable = model.getProjectListByCid(page, cid)
 .compose(ResponseTransformer.handleResult())
 .compose(scheduler?.applySchedulers())
 .subscribe(
 { t ->
 view?.getProjectListByCidSuccess(t, isRefresh)
 page++
 },
 { t -> view?.getProjectListByCidFail(t.message!!) }
 )
 compositeDisposable.add(disposable)
 }
 
这其中，在 view?.getProjectListByCidFail(t.message!!) 部分，这里并没有用到ApiException。这里的message 是ApiException中的message吗？

**Comment by YoloHuang** [comment]
谢谢，我看到了
    /**
     * 非服务器产生的异常，比如解析错误，网络连接错误
     */
    class ErrorResumeFunction<T> : Function<Throwable, ObservableSource<out Response<T>>> {
        override fun apply(t: Throwable): ObservableSource<out Response<T>> {
            return Observable.error(CustomException.handleException(t))
        }
    }

    /**
     * 服务器产生的错误：HTTP错误代码
     */
    class ResponseFunction<T> : Function<Response<T>, ObservableSource<T>> {
        override fun apply(t: Response<T>): ObservableSource<T> {
            val code: Int = t.errorCode
            return if (code >= 0) {
                Observable.just(t.data)
            } else {
                Observable.error(ApiException(t.errorMsg, null, code))
            }
        }

    }

按照这种封装，view?.getProjectListByCidFail(t.message!!)这个方法中的t，应该是ApiException对吗？

**Comment by YoloHuang** [comment]
看懂了，我看的是你这篇文章。https://www.jianshu.com/p/2e8b400909b7   这篇文章的代码跟这个项目的代码有区别。所以迷糊了半天。谢谢了！

**Comment by AxeChen** [comment]
谢谢支持！




------------------ 原始邮件 ------------------
发件人: "YoloHuang"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 下午2:57
收件人: "AxeChen/WanAndroid"<WanAndroid@noreply.github.com>;
抄送: "我们开始吧"<1137366723@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [AxeChen/WanAndroid] 关于rxjava +retrofit 封装网络访问 (#1)




看懂了，我看的是你这篇文章。https://www.jianshu.com/p/2e8b400909b7   这篇文章的代码跟这个项目的代码有区别。所以迷糊了半天。谢谢了！
